### ISSUE TITLE
💡 New release in the Actions marketplace

### ISSUE THREAD

**Issue by fabienrica-hexagon** [dariocurr/pytest-summary#17]
### Description

Hello @dariocurr, 

Would it be possible to make a new release of your GitHub action? The v2 still links to the old version of test-summary that gives a Node.js deprecation warning. I can see you already updated the dependency but it's not yet available as a versioned release.

Thanks for your time. If I can help with that, let me know!

### Basic Example

Warning message:

`The following actions use a deprecated Node.js version and will be forced to run on node20: test-summary/action@v2.1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/`
### Workaround

Use `dariocurr/pytest-summary@main`

**Comment by dariocurr** [comment]
I have updated tags and releases. Thanks for the heads up. I will add a workflow to automate it.

Please double-check that everything is back on track!

**Comment by dariocurr** [comment]
Thank you for your contribution!
