### ISSUE TITLE
Update test-summary/action to v2

### ISSUE THREAD

**Issue by nuhrberg** [dariocurr/pytest-summary#7]
Thank you for this awesome action. 
Exactly what I was looking for 🙂 

When I run a workflow with this action, I get the following error: 

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: test-summary/action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

`test-summary/action` already has a version 2 (and also a version 2.1) that uses node.js 16. 

It would be great if you could update the test-summary/action version. 🎉

**Comment by dariocurr** [comment]
Hi Nils. Thanks. I forgot to add dependabot to this project.
I hope this will happen automatically from now on.

Thank you for your contribution. Looking forward to knowing you more!

**Comment by nuhrberg** [comment]
> Hi Nils. Thanks. I forgot to add dependabot to this project. I hope this will happen automatically from now on.
> 
> Thank you for your contribution. Looking forward to knowing you more!

Hi Dario 👋 , 
you're welcome. That's what open source software is all about. 🙂
